// Sample product data for local development / testing.
// Run with: npm run seed  (wipes the products collection and reinserts this list)

export const seedProducts = [
  // ---------- clothes ----------
  {
    slug: "harbor-wool-coat",
    name: "Harbor Wool Coat",
    category: "clothes",
    brand: "Fieldnote",
    price: 220,
    salePrice: 176,
    onSale: true,
    isNewArrival: false,
    rating: 4.7,
    reviews: 54,
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Camel"],
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=1200&auto=format&fit=crop"],
    description: "A heavyweight wool coat cut for layering, with a half-belt back and horn buttons.",
    details: ["80% wool, 20% nylon blend", "Dry clean only", "Half-belt back, welt pockets"],
  },
  {
    slug: "essential-cotton-tee",
    name: "Essential Cotton Tee",
    category: "clothes",
    brand: "Fieldnote",
    price: 28,
    onSale: false,
    isNewArrival: true,
    rating: 4.5,
    reviews: 132,
    stock: 60,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Sage"],
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1200&auto=format&fit=crop"],
    description: "A midweight, garment-dyed tee that softens with every wash. Boxy, relaxed fit.",
    details: ["100% combed cotton", "Machine washable, cold", "Relaxed fit"],
  },
  {
    slug: "trail-canvas-pants",
    name: "Trail Canvas Pants",
    category: "clothes",
    brand: "Fieldnote",
    price: 84,
    onSale: false,
    isNewArrival: false,
    rating: 4.6,
    reviews: 41,
    stock: 26,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Olive", "Stone"],
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1200&auto=format&fit=crop"],
    description: "Heavy cotton canvas work pants with a tapered leg and reinforced knees.",
    details: ["100% cotton canvas", "Reinforced knees", "Tapered fit"],
  },

  // ---------- gym-equipment ----------
  {
    slug: "cast-iron-kettlebell-16kg",
    name: "Cast Iron Kettlebell, 16kg",
    category: "gym-equipment",
    brand: "Ironhold",
    price: 62,
    onSale: false,
    isNewArrival: false,
    rating: 4.8,
    reviews: 76,
    stock: 34,
    sizes: [],
    colors: ["Black"],
    image: "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1517963879433-6ad2b056d712?q=80&w=1200&auto=format&fit=crop"],
    description: "Single-cast iron kettlebell with a wide, flat base and a smooth powder-coat handle.",
    details: ["16kg / 35lb", "Wide flat base for stability", "Powder-coated finish"],
  },
  {
    slug: "pro-yoga-mat",
    name: "Pro Yoga Mat",
    category: "gym-equipment",
    brand: "Ironhold",
    price: 48,
    salePrice: 36,
    onSale: true,
    isNewArrival: true,
    rating: 4.6,
    reviews: 98,
    stock: 50,
    sizes: [],
    colors: ["Slate", "Moss"],
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=1200&auto=format&fit=crop"],
    description: "6mm closed-cell foam mat with a textured non-slip surface on both sides.",
    details: ["6mm thickness", "183 x 66cm", "Non-slip both sides, includes carry strap"],
  },
  {
    slug: "adjustable-dumbbell-set",
    name: "Adjustable Dumbbell Set",
    category: "gym-equipment",
    brand: "Ironhold",
    price: 249,
    onSale: false,
    isNewArrival: false,
    rating: 4.9,
    reviews: 63,
    stock: 9,
    sizes: [],
    colors: ["Black/Red"],
    image: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=1200&auto=format&fit=crop"],
    description: "Dial-adjustable dumbbell pair, 5–52.5lb each in 2.5lb increments. Replaces 15 pairs.",
    details: ["5–52.5lb per dumbbell, 2.5lb increments", "Sold as a pair", "Includes storage tray"],
  },

  // ---------- home-appliances ----------
  {
    slug: "pour-over-kettle",
    name: "Gooseneck Pour-Over Kettle",
    category: "home-appliances",
    brand: "Kindle & Co",
    price: 68,
    onSale: false,
    isNewArrival: true,
    rating: 4.7,
    reviews: 45,
    stock: 22,
    sizes: [],
    colors: ["Matte Black", "Brushed Steel"],
    image: "https://images.unsplash.com/photo-1620705797257-c5824f3e4a1a?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1620705797257-c5824f3e4a1a?q=80&w=1200&auto=format&fit=crop"],
    description: "Precision gooseneck spout for steady, controlled pours. Built-in thermometer on the lid.",
    details: ["1L capacity", "Stovetop compatible, incl. induction", "Built-in dial thermometer"],
  },
  {
    slug: "compact-air-purifier",
    name: "Compact Air Purifier",
    category: "home-appliances",
    brand: "Kindle & Co",
    price: 129,
    salePrice: 99,
    onSale: true,
    isNewArrival: false,
    rating: 4.5,
    reviews: 88,
    stock: 15,
    sizes: [],
    colors: ["White"],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=1200&auto=format&fit=crop"],
    description: "True HEPA filtration for rooms up to 250 sq ft, with a near-silent sleep mode.",
    details: ["True HEPA + activated carbon filter", "Covers up to 250 sq ft", "Sleep mode: 24dB"],
  },
  {
    slug: "stand-mixer",
    name: "5-Quart Stand Mixer",
    category: "home-appliances",
    brand: "Kindle & Co",
    price: 349,
    onSale: false,
    isNewArrival: false,
    rating: 4.9,
    reviews: 120,
    stock: 7,
    sizes: [],
    colors: ["Cream", "Slate Blue"],
    image: "https://images.unsplash.com/photo-1594221708779-94832f4320d1?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1594221708779-94832f4320d1?q=80&w=1200&auto=format&fit=crop"],
    description: "Die-cast metal stand mixer with a tilt-head design and three included attachments.",
    details: ["5-quart stainless bowl", "Includes whisk, dough hook, flat beater", "10-speed motor"],
  },

  // ---------- pc-setup ----------
  {
    slug: "mechanical-keyboard-75",
    name: "75% Mechanical Keyboard",
    category: "pc-setup",
    brand: "Circuit & Bell",
    price: 139,
    onSale: false,
    isNewArrival: true,
    rating: 4.8,
    reviews: 67,
    stock: 30,
    sizes: [],
    colors: ["Graphite"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop"],
    description: "Hot-swappable 75% layout with gasket-mounted plate and PBT keycaps.",
    details: ["Hot-swappable switches", "Gasket-mounted plate", "USB-C, wired"],
  },
  {
    slug: "ultrawide-monitor-34",
    name: "34\" Ultrawide Monitor",
    category: "pc-setup",
    brand: "Circuit & Bell",
    price: 449,
    salePrice: 379,
    onSale: true,
    isNewArrival: false,
    rating: 4.7,
    reviews: 39,
    stock: 5,
    sizes: [],
    colors: ["Black"],
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1200&auto=format&fit=crop"],
    description: "3440x1440 curved ultrawide with 144Hz refresh and USB-C 90W passthrough.",
    details: ["3440x1440, 144Hz, 1500R curve", "USB-C with 90W power delivery", "Height & tilt adjustable stand"],
  },
  {
    slug: "desk-cable-management-tray",
    name: "Under-Desk Cable Tray",
    category: "pc-setup",
    brand: "Circuit & Bell",
    price: 34,
    onSale: false,
    isNewArrival: false,
    rating: 4.4,
    reviews: 22,
    stock: 45,
    sizes: [],
    colors: ["Black", "White"],
    image: "https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=1200&auto=format&fit=crop"],
    description: "Clamp-mount steel tray that keeps power strips and cable clutter off the floor.",
    details: ["Steel construction, clamp mount", "45 x 15cm", "No drilling required"],
  },

  // ---------- furniture ----------
  {
    slug: "field-oak-stool",
    name: "Field Oak Stool",
    category: "furniture",
    brand: "Bells Home",
    price: 145,
    onSale: false,
    isNewArrival: true,
    rating: 4.7,
    reviews: 21,
    stock: 8,
    sizes: [],
    colors: ["Natural Oak"],
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=1200&auto=format&fit=crop"],
    description: "Solid European oak, finger-jointed for strength without a single screw.",
    details: ["Solid oak, natural oil finish", "45cm height, holds up to 150kg", "Assembly-free, one piece"],
  },
  {
    slug: "hearth-walnut-tray",
    name: "Hearth Walnut Tray",
    category: "furniture",
    brand: "Bells Home",
    price: 64,
    onSale: false,
    isNewArrival: false,
    rating: 4.6,
    reviews: 33,
    stock: 25,
    sizes: [],
    colors: ["Walnut"],
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=1200&auto=format&fit=crop"],
    description: "A single slab of American walnut with brass handles.",
    details: ["Solid walnut, brass handles", "40 x 28cm", "Hand wash, oil occasionally"],
  },
  {
    slug: "linden-accent-chair",
    name: "Linden Accent Chair",
    category: "furniture",
    brand: "Bells Home",
    price: 320,
    salePrice: 256,
    onSale: true,
    isNewArrival: false,
    rating: 4.8,
    reviews: 29,
    stock: 6,
    sizes: [],
    colors: ["Oat Boucle", "Clay"],
    image: "https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=1200&auto=format&fit=crop"],
    description: "A low, wide accent chair with a solid beech frame and boucle upholstery.",
    details: ["Solid beech frame", "Removable boucle cushion cover", "68 x 74 x 76cm"],
  },
];
